sudo: required
service:
 - docker
before_install:
  - docker build -t lavanyacnl/travis1:v2.0 .
script:
 - echo "$docker_password" | docker login -u "$docker_username" --password-stdin
 - docker images # to verify image is build or not
 - docker push lavanyacnl/travis1:v2.0
notifications:
 email:
   recipients:
     - lavanya96757@gmail.com
   on_success: always
   on_failure: always
